import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
    Play, Pause, Music, Mic2, Download, Heart, Share2, Disc, Wand2, Volume2,
    SkipBack, SkipForward, Radio, Sparkles, X, BookOpen, Save, RefreshCw, Layers,
    Menu, Info, ChevronLeft, Image as ImageIcon, Link, Check, Copy, FileText, MessageSquare, Book, PenTool, Eraser,
    Settings, Moon, Sun, Globe, Type as TypeIcon, HelpCircle, ChevronDown, ChevronUp, Edit3, Loader2, Square, Maximize2, Minimize2, ZoomIn, ZoomOut, List
} from 'lucide-react';

import { contentTypesData } from './constants';
import { ContentTypeKey, Song, Note, DictionaryResult, ImagePrompt, ViewState } from './types';
import * as Gemini from './services/geminiService';
import { Type } from '@google/genai';

// --- Localization & Constants ---
const UI_TEXT = {
    English: {
        nav: { create: "Create", library: "Library", notes: "Notes", dictionary: "Dictionary", about: "About", settings: "Settings" },
        headers: { aiDrafter: "AI Drafter", result: "Generated Result & Editor", styleConfig: "Style Config", simulate: "Simulate Output", visual: "Visual Storyboard" },
        settings: { title: "Settings", theme: "Appearance", language: "Language", fontSize: "Font Size" },
        about: { title: "About NEPCON AI", faq: "Frequently Asked Questions" }
    },
    Nepali: {
        nav: { create: "सिर्जना (Create)", library: "पुस्तकालय (Library)", notes: "नोटहरू (Notes)", dictionary: "शब्दकोश (Dictionary)", about: "बारेमा (About)", settings: "सेटिङ (Settings)" },
        headers: { aiDrafter: "AI मस्यौदाकार", result: "सिर्जना र सम्पादन", styleConfig: "शैली कन्फिगरेसन", simulate: "अडियो सिमुलेशन", visual: "दृश्य स्टोरीबोर्ड" },
        settings: { title: "सेटिङहरू", theme: "रूप (Appearance)", language: "भाषा (Language)", fontSize: "फन्ट साइज" },
        about: { title: "नेपकन एआई प्रो को बारेमा", faq: "प्राय: सोधिने प्रश्नहरू" }
    },
    Hindi: {
        nav: { create: "बनाएं (Create)", library: "लाइब्रेरी (Library)", notes: "नोट्स (Notes)", dictionary: "शब्दकोश (Dictionary)", about: "बारे में (About)", settings: "सेटिंग्स (Settings)" },
        headers: { aiDrafter: "AI ड्राफ्टर", result: "परिणाम और संपादक", styleConfig: "शैली विन्यास", simulate: "ऑडियो सिमुलेशन", visual: "दृश्य स्टोरीबोर्ड" },
        settings: { title: "सेटिंग्स", theme: "दिखावट (Appearance)", language: "भाषा (Language)", fontSize: "फ़ॉन्ट आकार" },
        about: { title: "नेपकन एआई प्रो के बारे में", faq: "अक्सर पूछे जाने वाले प्रश्न" }
    }
};

const FAQS = [
    { q: "What is NEPCON AI Pro?", a: "NEPCON AI Pro is a multi-modal content generation tool designed specifically for Nepali and South Asian creators, powered by Google's Gemini AI." },
    { q: "Is the content copyright free?", a: "Yes, the content generated by AI is unique. However, we recommend reviewing it before commercial use." },
    { q: "How does the Music Simulation work?", a: "Currently, it simulates the metadata and structure of a song. Audio synthesis integration is coming in future updates." },
    { q: "Can I use it offline?", a: "No, an active internet connection is required to communicate with the Gemini AI models." },
    { q: "How do I save my work?", a: "You can save drafts to the 'Notes' section within the app or copy them to your clipboard." }
];

export default function App() {
    // --- State: Settings & UI ---
    const [theme, setTheme] = useState<'dark' | 'light'>('dark');
    const [appLanguage, setAppLanguage] = useState<'English' | 'Nepali' | 'Hindi'>('English');
    const [fontSize, setFontSize] = useState<'small' | 'medium' | 'large'>('medium');
    const [currentView, setCurrentView] = useState<ViewState>('CREATE');
    const [isMenuOpen, setIsMenuOpen] = useState(false);
    const [maximizedSection, setMaximizedSection] = useState<'DRAFTER' | 'RESULT' | 'SB_PROMPT' | null>(null);

    // --- State: Content ---
    const [contentType, setContentType] = useState<ContentTypeKey>('Music');
    const [content, setContent] = useState("");
    const [title, setTitle] = useState("Pandhra Minute (15 Minutes)");
    
    // --- State: Styles ---
    const [styleSelection, setStyleSelection] = useState(contentTypesData['Music'].defaultStyleSelection);
    const [customStyle, setCustomStyle] = useState("");
    const [styleDetails, setStyleDetails] = useState(contentTypesData['Music'].defaultStyleDetails);

    // --- State: App Flow ---
    const [isGenerating, setIsGenerating] = useState(false);
    const [isAiLoading, setIsAiLoading] = useState(false);
    const [errorMsg, setErrorMsg] = useState("");

    // --- State: AI Drafting ---
    const [aiPrompt, setAiPrompt] = useState("");
    const [isCopied, setIsCopied] = useState(false);

    // --- State: Playback/Data ---
    const [generatedSongs, setGeneratedSongs] = useState<Song[]>([]);
    const [currentSong, setCurrentSong] = useState<Song | null>(null);
    const [isPlaying, setIsPlaying] = useState(false);
    const [currentTime, setCurrentTime] = useState(0);
    const [duration, setDuration] = useState(0);
    const [notes, setNotes] = useState<Note[]>([]);

    // --- State: Dictionary ---
    const [dictionaryQuery, setDictionaryQuery] = useState("माया");
    const [dictionaryResults, setDictionaryResults] = useState<DictionaryResult[]>([]);

    // --- State: Image Generation ---
    const [showMusicOptions, setShowMusicOptions] = useState(false);
    const [showImageFlow, setShowImageFlow] = useState(false);
    const [imagePrompts, setImagePrompts] = useState<ImagePrompt[]>([]);
    const [isImagePrompting, setIsImagePrompting] = useState(false);
    const [isImageGenerating, setIsImageGenerating] = useState(false);
    const [selectedImagePromptIndex, setSelectedImagePromptIndex] = useState(0);
    const [promptCount, setPromptCount] = useState(3);
    const [expandedFaqIndex, setExpandedFaqIndex] = useState<number | null>(null);
    const [imageFitMode, setImageFitMode] = useState<'contain' | 'cover'>('contain');
    const [isMobileSceneListOpen, setIsMobileSceneListOpen] = useState(false);

    // --- Refs ---
    const stopGenerationRef = useRef(false);

    const currentContentTypeData = contentTypesData[contentType];
    const ui = UI_TEXT[appLanguage];

    // Helper for Theme Classes
    const getThemeClasses = () => {
        const isDark = theme === 'dark';
        return {
            bg: isDark ? 'bg-gray-950' : 'bg-gray-50',
            bgSidebar: isDark ? 'bg-gray-950' : 'bg-white',
            bgCard: isDark ? 'bg-gray-900' : 'bg-white',
            bgInput: isDark ? 'bg-gray-800' : 'bg-gray-100',
            text: isDark ? 'text-gray-100' : 'text-gray-900',
            textMuted: isDark ? 'text-gray-400' : 'text-gray-500',
            border: isDark ? 'border-gray-800' : 'border-gray-200',
            borderInput: isDark ? 'border-gray-700' : 'border-gray-300',
            accent: 'text-rose-600',
            primaryBtn: 'bg-rose-600 hover:bg-rose-700 text-white',
        };
    };

    const tc = getThemeClasses();
    const fontSizeClass = fontSize === 'small' ? 'text-xs' : fontSize === 'large' ? 'text-lg' : 'text-sm';

    // --- Effects ---

    useEffect(() => {
        const data = contentTypesData[contentType];
        setStyleSelection(data.defaultStyleSelection);
        setStyleDetails(data.defaultStyleDetails);
        setCustomStyle("");
        setTitle(`Untitled ${data.label.split('(')[0].trim()}`);
        setAiPrompt("");
        setShowImageFlow(false);
        setImagePrompts([]);
    }, [contentType]);

    useEffect(() => {
        let interval: NodeJS.Timeout;
        if (isPlaying && currentSong) {
            interval = setInterval(() => {
                setCurrentTime(prev => {
                    if (prev >= duration) {
                        setIsPlaying(false);
                        return 0;
                    }
                    return prev + 1;
                });
            }, 1000);
        }
        return () => clearInterval(interval);
    }, [isPlaying, currentSong, duration]);

    // --- Handlers ---
    
    const formatTime = (seconds: number) => {
        const mins = Math.floor(seconds / 60);
        const secs = seconds % 60;
        return `${mins}:${secs.toString().padStart(2, '0')}`;
    };

    const handleCopyContent = () => {
        if (!content.trim()) return;
        navigator.clipboard.writeText(content);
        setIsCopied(true);
        setTimeout(() => setIsCopied(false), 2000);
    };

    const handleSaveDraftToNotes = () => {
        if (!content.trim()) {
            setErrorMsg("Cannot save empty draft.");
            setTimeout(() => setErrorMsg(""), 3000);
            return;
        }
        const finalStyle = styleSelection === "Other..." && customStyle ? customStyle : styleSelection;
        const newNote: Note = {
            id: Date.now(),
            title: title || `Untitled Draft`,
            type: contentType,
            summary: content.substring(0, 80) + '...',
            fullContent: content,
            style: `${finalStyle}`,
            date: new Date().toLocaleDateString()
        };
        setNotes([newNote, ...notes]);
        setErrorMsg("Draft saved to Notes!");
        setTimeout(() => setErrorMsg(""), 3000);
    };

    const handleSuggestStyle = async () => {
        if (!content.trim()) return;
        setIsAiLoading(true);
        const prompt = `Based on this content (Title: ${title}, Type: ${currentContentTypeData.label}, Draft: ${content}), suggest a primary style and detailed tags. Output strictly as: StyleName###DetailedTags`;
        const result = await Gemini.generateText(prompt, "You are a creative editor. Output ONLY the requested format.");
        if (result) {
            const parts = result.split('###').map(p => p.trim());
            if (parts.length === 2) {
                if (currentContentTypeData.selectionList.includes(parts[0])) {
                    setStyleSelection(parts[0]);
                    setCustomStyle("");
                } else {
                    setStyleSelection("Other...");
                    setCustomStyle(parts[0]);
                }
                setStyleDetails(parts[1]);
            }
        }
        setIsAiLoading(false);
    };

    const handleAiContentGeneration = async () => {
        if (!aiPrompt.trim()) return;
        setIsAiLoading(true);
        const finalStyle = styleSelection === "Other..." ? customStyle : styleSelection;
        const prompt = `Write high-quality ${currentContentTypeData.label} about: "${aiPrompt}". Style: ${finalStyle}, ${styleDetails}. Language: ${appLanguage === 'Nepali' ? 'Nepali' : appLanguage === 'Hindi' ? 'Hindi' : 'English/Nepali Mix'}. Output ONLY the generated content text.`;
        const text = await Gemini.generateText(prompt, `You are a professional content creator for ${currentContentTypeData.label}.`);
        if (text) setContent(text);
        setIsAiLoading(false);
        if (maximizedSection === 'DRAFTER') setMaximizedSection(null);
    };

    const handleRefinePrompt = async () => {
        if (!aiPrompt.trim()) return;
        setIsAiLoading(true);
        const prompt = `Refine this prompt to be more descriptive, creative, and specific for an AI content generator. Keep the language consistent. Prompt: "${aiPrompt}"`;
        const text = await Gemini.generateText(prompt, "You are an expert prompt engineer. Output only the refined prompt.");
        if (text) setAiPrompt(text);
        setIsAiLoading(false);
    };

    const handleDictionarySearch = async () => {
        if (!dictionaryQuery.trim()) return;
        setDictionaryResults([]);
        setIsAiLoading(true);
        const prompt = `Find 5 words that rhyme with '${dictionaryQuery}' in Nepali, Hindi, or Sanskrit.`;
        const schema = {
            type: Type.ARRAY,
            items: {
                type: Type.OBJECT,
                properties: { word: { type: Type.STRING }, language: { type: Type.STRING }, meaning: { type: Type.STRING } },
                required: ["word", "language", "meaning"]
            }
        };
        const data = await Gemini.generateStructuredData(prompt, "You are a rhyme dictionary.", schema);
        if (data) setDictionaryResults(data);
        else setErrorMsg("Failed to fetch rhymes.");
        setIsAiLoading(false);
    };

    const handleBreakdownContent = async () => {
        if (!content.trim()) { setErrorMsg("Please enter content first."); return; }
        setIsImagePrompting(true);
        const count = Math.max(1, Math.min(10, promptCount));
        const prompt = `Break down this ${currentContentTypeData.label} into ${count} cinematic image prompts.`;
        const schema = {
            type: Type.ARRAY,
            items: {
                type: Type.OBJECT,
                properties: { id: { type: Type.INTEGER }, prompt_en: { type: Type.STRING }, prompt_ne: { type: Type.STRING } },
                required: ["id", "prompt_en", "prompt_ne"]
            }
        };
        const data = await Gemini.generateStructuredData(prompt + `\n\nContent: ${content}`, "You are a visual director.", schema);
        if (data) {
            const formatted = data.map((p: any) => ({ 
                id: p.id, 
                prompt: p.prompt_en, 
                summary_ne: p.prompt_ne, 
                status: 'pending' 
            }));
            setImagePrompts(formatted);
            setSelectedImagePromptIndex(0);
        }
        setIsImagePrompting(false);
    };

    const generateSingleImage = async (index: number) => {
        const currentP = imagePrompts[index];
        if (!currentP) return;

        // Optimistic UI update
        const updatedPrompts = [...imagePrompts];
        updatedPrompts[index].status = 'loading';
        setImagePrompts(updatedPrompts);
        
        const enhancedPrompt = `${currentP.prompt}, cinematic, 8k, highly detailed, atmospheric lighting`;
        const b64 = await Gemini.generateImageContent(enhancedPrompt);
        
        // Because checking strict equality of array ref in React state, use functional update to ensure latest state if called in loop
        setImagePrompts(prev => {
            const next = [...prev];
            if (b64) {
                next[index] = { ...next[index], status: 'generated', imageUrl: b64 };
            } else {
                next[index] = { ...next[index], status: 'error' };
            }
            return next;
        });
    };

    const handleGenerateImage = async () => {
        setIsImageGenerating(true);
        await generateSingleImage(selectedImagePromptIndex);
        setIsImageGenerating(false);
    };

    const handleGenerateAllImages = async () => {
        stopGenerationRef.current = false;
        setIsImageGenerating(true);
        // Sequential generation to avoid potential rate limits or browser lag with multiple canvas ops
        for (let i = 0; i < imagePrompts.length; i++) {
             if (stopGenerationRef.current) break;
             // Only generate if not already generated to save credits/time, 
             if (imagePrompts[i].status !== 'generated') {
                await generateSingleImage(i);
             }
        }
        setIsImageGenerating(false);
    };

    const handleStopGeneration = () => {
        stopGenerationRef.current = true;
        setIsImageGenerating(false);
    };

    const handlePromptChange = (index: number, newText: string) => {
        const newPrompts = [...imagePrompts];
        newPrompts[index].prompt = newText;
        setImagePrompts(newPrompts);
    };

    const handleDownloadImage = (url: string, id: number) => {
        const link = document.createElement('a');
        link.href = url;
        link.download = `nepcon-scene-${id}.png`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    const handleSimulateMusic = () => {
        const colors = ['bg-rose-500', 'bg-indigo-500', 'bg-emerald-500', 'bg-purple-500', 'bg-sky-500'];
        const newSong: Song = {
            id: Date.now(),
            title: title || "Untitled Track",
            style: styleSelection,
            date: new Date().toLocaleDateString(),
            duration: 180 + Math.floor(Math.random() * 60),
            coverColor: colors[Math.floor(Math.random() * colors.length)],
            lyrics: content
        };
        setGeneratedSongs([newSong, ...generatedSongs]);
        setCurrentSong(newSong);
        setDuration(newSong.duration);
        setCurrentTime(0);
        setIsPlaying(true);
        setShowMusicOptions(false);
        setErrorMsg("Simulated music generated!");
        setTimeout(() => setErrorMsg(""), 3000);
    };

    const togglePlay = (song: Song) => {
        if (currentSong?.id === song.id) {
            setIsPlaying(!isPlaying);
        } else {
            setCurrentSong(song);
            setDuration(song.duration);
            setCurrentTime(0);
            setIsPlaying(true);
        }
    };

    // --- Renderers ---

    const renderSidebar = () => (
        <div className={`fixed inset-y-0 left-0 z-40 w-64 ${tc.bgSidebar} border-r ${tc.border} transform transition-transform duration-300 ease-in-out flex flex-col ${isMenuOpen ? 'translate-x-0' : '-translate-x-full'}`}>
            {/* Nepali Dhaka Topi Inspired Header Border */}
            <div className="h-2 w-full bg-gradient-to-r from-red-600 via-green-600 to-blue-600"></div>
            
            <div className={`p-6 flex items-center justify-between border-b ${tc.border}`}>
                <div onClick={() => window.location.reload()} className="flex items-center gap-3 text-rose-600 cursor-pointer hover:opacity-80 transition-opacity">
                    <Music size={24} />
                    <h1 className={`text-xl font-bold tracking-tight ${tc.text}`}>NEPCON AI</h1>
                </div>
                <button onClick={() => setIsMenuOpen(false)} className={`${tc.textMuted} hover:${tc.text} p-2`}><ChevronLeft size={24} /></button>
            </div>
            
            <nav className="flex-1 px-4 py-4 space-y-2">
                {[
                    { id: 'CREATE', label: ui.nav.create, icon: Wand2, color: 'text-rose-500' },
                    { id: 'GENERATED', label: ui.nav.library, icon: Disc, color: 'text-sky-500' },
                    { id: 'NOTES', label: ui.nav.notes, icon: Layers, color: 'text-amber-500' },
                    { id: 'DICTIONARY', label: ui.nav.dictionary, icon: BookOpen, color: 'text-emerald-500' },
                    { id: 'ABOUT', label: ui.nav.about, icon: Info, color: 'text-indigo-500' },
                    { id: 'SETTINGS', label: ui.nav.settings, icon: Settings, color: 'text-gray-500' },
                ].map(item => (
                    <button
                        key={item.id}
                        onClick={() => { setCurrentView(item.id as any); setIsMenuOpen(false); }}
                        className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all text-left ${currentView === item.id ? `bg-gray-200 dark:bg-gray-800 ${tc.text} font-bold shadow-sm` : `${tc.textMuted} hover:${tc.text} hover:bg-gray-100 dark:hover:bg-gray-900`}`}
                    >
                        <item.icon size={20} className={item.color} />
                        <span className={fontSizeClass}>{item.label}</span>
                    </button>
                ))}
            </nav>
            
            {/* Footer / Credits */}
            <div className={`p-4 border-t ${tc.border} text-xs ${tc.textMuted} text-center`}>
                 <p>© 2024 NEPCON AI Pro</p>
                 <p>Made with ❤️ in Nepal</p>
            </div>
        </div>
    );

    const renderContentEditor = () => {
        return (
            <div className="h-full flex flex-col space-y-4">
                {/* AI Prompt Section */}
                <div className={`${tc.bgCard} p-4 rounded-2xl border ${tc.border} flex flex-col gap-3 relative overflow-hidden group shadow-lg`}>
                    <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-rose-500 to-indigo-600"></div>
                    <div className="flex justify-between items-center">
                         <label className={`text-sm font-bold text-indigo-400 flex items-center gap-2`}><Sparkles size={16} /> {ui.headers.aiDrafter}</label>
                         <div className="flex items-center gap-2">
                            {aiPrompt && <button onClick={() => setAiPrompt('')} className="text-xs text-gray-400 hover:text-rose-500"><Eraser size={12} /></button>}
                            <button onClick={() => setMaximizedSection('DRAFTER')} className="text-xs text-indigo-500 hover:text-indigo-400 p-1"><Maximize2 size={14}/></button>
                         </div>
                    </div>
                    <textarea
                        value={aiPrompt}
                        onChange={(e) => setAiPrompt(e.target.value)}
                        placeholder={`Describe the ${currentContentTypeData.label} you want to create...`}
                        className={`w-full ${tc.bgInput} border ${tc.borderInput} rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-rose-500/50 resize-none ${tc.text} h-24 transition-all`}
                        style={{ fontSize: fontSize === 'large' ? '16px' : '14px' }}
                    />
                    <div className="flex justify-between items-center">
                        <div className={`text-xs ${tc.textMuted} flex gap-2`}>
                            <span className={`${tc.bgInput} px-2 py-1 rounded border ${tc.borderInput}`}>Style: {styleSelection}</span>
                        </div>
                        <div className="flex gap-2">
                            <button 
                                onClick={handleAiContentGeneration} 
                                disabled={isAiLoading || !aiPrompt.trim()} 
                                className={`px-6 py-2 rounded-xl text-sm font-bold bg-rose-600 hover:bg-rose-700 text-white flex justify-center items-center gap-2 shadow-lg shadow-rose-500/20 transition-all active:scale-95 disabled:opacity-50`}
                            >
                                {isAiLoading ? <div className="animate-spin h-4 w-4 border-2 border-white rounded-full border-t-transparent"/> : <Sparkles size={16} />} 
                                Generate
                            </button>
                            <button 
                                onClick={handleRefinePrompt} 
                                disabled={isAiLoading || !aiPrompt.trim()} 
                                className={`px-4 py-2 rounded-xl text-sm font-bold ${tc.bgInput} hover:bg-gray-700 text-gray-300 flex justify-center items-center gap-2 transition-all border ${tc.borderInput}`}
                            >
                                <Wand2 size={14} /> Refine
                            </button>
                        </div>
                    </div>
                </div>

                {/* Main Content Result */}
                <div className={`flex-1 flex flex-col relative ${tc.bgCard} border ${tc.border} rounded-2xl overflow-hidden shadow-lg`}>
                    <div className={`px-4 py-2 border-b ${tc.border} ${tc.bgInput} flex justify-between items-center`}>
                        <label className={`text-xs font-bold ${tc.textMuted} uppercase tracking-wider`}>{ui.headers.result}</label>
                        <button onClick={() => setMaximizedSection('RESULT')} className="text-xs text-indigo-500 hover:text-indigo-400 p-1"><Maximize2 size={14}/></button>
                    </div>
                    
                    <textarea
                        value={content}
                        onChange={(e) => setContent(e.target.value)}
                        className={`flex-1 w-full ${tc.bgCard} px-5 py-4 focus:outline-none font-mono leading-relaxed resize-none ${tc.text} placeholder-gray-600`}
                        style={{ fontSize: fontSize === 'large' ? '16px' : '13px' }}
                        placeholder="Generated content will appear here. You can also edit manually."
                    />

                    <div className={`flex justify-end items-center gap-3 px-4 py-3 border-t ${tc.border} ${tc.bgInput}`}>
                         <button onClick={handleCopyContent} disabled={!content.trim()} className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs transition-all font-medium border ${isCopied ? 'bg-green-600 text-white border-green-500' : `${tc.bgCard} hover:${tc.bgSidebar} ${tc.textMuted} ${tc.borderInput}`}`}>
                            {isCopied ? <Check size={14} /> : <Copy size={14} />} {isCopied ? 'Copied' : 'Copy'}
                         </button>
                         <button onClick={handleSaveDraftToNotes} disabled={!content.trim()} className="flex items-center gap-2 px-4 py-2 bg-amber-600 hover:bg-amber-700 rounded-lg text-xs text-white transition-all font-medium border border-amber-500 shadow-lg shadow-amber-900/20"><Save size={14} /> Save</button>
                    </div>
                </div>
            </div>
        );
    };

    return (
        <div className={`flex h-screen ${tc.bg} ${tc.text} font-sans overflow-hidden transition-colors duration-300`}>
            {renderSidebar()}
            {isMenuOpen && <div onClick={() => setIsMenuOpen(false)} className="fixed inset-0 bg-black/50 z-30 md:hidden" />}

            <div className="flex-1 flex flex-col relative transition-all duration-300">
                {/* Top Bar */}
                <div className={`h-16 ${tc.bgSidebar} backdrop-blur-md border-b ${tc.border} px-4 flex items-center justify-between z-20`}>
                    <div className="flex items-center gap-3">
                        <button onClick={() => setIsMenuOpen(true)} className={`p-2 rounded-full hover:${tc.bgInput} ${tc.text}`}><Menu size={24} /></button>
                        <div onClick={() => window.location.reload()} className="hidden md:flex items-center gap-2 text-rose-600 cursor-pointer hover:opacity-80 transition-opacity">
                            <Wand2 size={24} />
                            <span className={`font-bold text-xl ${tc.text}`}>NEPCON AI Pro</span>
                        </div>
                    </div>
                    {currentView !== 'CREATE' && (
                        <button onClick={() => setCurrentView('CREATE')} className={`flex items-center gap-1 text-sm ${tc.textMuted} hover:text-rose-500 transition-colors`}>
                            <Wand2 size={16} /> {ui.nav.create}
                        </button>
                    )}
                </div>

                {/* Main View Area */}
                <div className={`flex-1 overflow-y-auto ${tc.bg} relative p-4`}>
                    {/* Error Toast */}
                    {errorMsg && (
                        <div className="absolute top-4 right-4 z-50 bg-red-500/90 text-white px-4 py-2 rounded-lg shadow-lg flex items-center gap-2 animate-bounce-slow">
                            <Info size={16} /> {errorMsg}
                        </div>
                    )}

                    {currentView === 'CREATE' && (
                        <div className="max-w-6xl mx-auto md:p-4 space-y-6">
                             {/* Header Input Area */}
                             <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                                <div className="col-span-1 md:col-span-2 space-y-4">
                                    <div className={`${tc.bgCard} p-1 rounded-xl flex gap-1 border ${tc.border}`}>
                                        {(Object.keys(contentTypesData) as ContentTypeKey[]).map((key) => {
                                            const Icon = contentTypesData[key].icon;
                                            return (
                                            <button
                                                key={key}
                                                onClick={() => setContentType(key)}
                                                className={`flex-1 py-2 rounded-lg text-xs font-bold transition-all flex justify-center items-center gap-1 ${contentType === key ? `bg-${contentTypesData[key].themeColor}-600 text-white shadow-lg` : `${tc.textMuted} hover:${tc.text}`}`}
                                            >
                                                <Icon size={14} className={contentType === key ? "text-white" : contentTypesData[key].themeColor ? `text-${contentTypesData[key].themeColor}-500` : ""} />
                                                <span className="hidden sm:inline">{contentTypesData[key].label.split('(')[0]}</span>
                                            </button>
                                            );
                                        })}
                                    </div>
                                    <input 
                                        value={title} 
                                        onChange={e => setTitle(e.target.value)} 
                                        className={`w-full bg-transparent text-3xl font-bold placeholder-gray-500 focus:outline-none ${tc.text} border-b border-transparent focus:border-rose-500 transition-colors pb-2`} 
                                        placeholder="Enter Title..."
                                    />
                                </div>
                                
                                {/* Style Config */}
                                <div className={`space-y-2 ${tc.bgCard} p-4 rounded-xl border ${tc.border}`}>
                                    <div className={`flex justify-between items-center text-xs ${tc.textMuted}`}>
                                        <span className="uppercase tracking-wider font-bold">{ui.headers.styleConfig}</span>
                                        <button onClick={handleSuggestStyle} disabled={isAiLoading || !content} className="text-rose-500 hover:underline flex items-center gap-1"><Sparkles size={10} /> Suggest</button>
                                    </div>
                                    <select value={styleSelection} onChange={(e) => setStyleSelection(e.target.value)} className={`w-full ${tc.bgInput} border ${tc.borderInput} rounded-lg px-3 py-2 text-sm focus:ring-1 focus:ring-rose-500 ${tc.text}`}>
                                        {currentContentTypeData.selectionList.map(s => <option key={s} value={s}>{s}</option>)}
                                    </select>
                                    {styleSelection === 'Other...' && <input value={customStyle} onChange={e => setCustomStyle(e.target.value)} placeholder="Custom Style" className={`w-full ${tc.bgInput} border ${tc.borderInput} rounded-lg px-3 py-2 text-sm ${tc.text}`} />}
                                    <textarea value={styleDetails} onChange={e => setStyleDetails(e.target.value)} rows={2} className={`w-full ${tc.bgInput} border ${tc.borderInput} rounded-lg px-3 py-2 text-xs ${tc.textMuted} resize-none`} />
                                </div>
                             </div>

                             {/* Main Work Area */}
                             <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 h-auto lg:h-[600px]">
                                {renderContentEditor()}
                                
                                <div className="flex flex-col gap-4 h-full">
                                    <button onClick={() => contentType === 'Music' ? setShowMusicOptions(true) : setErrorMsg("Simulation only available for music currently.")} className="flex-1 bg-gradient-to-br from-rose-600 to-rose-700 hover:from-rose-500 hover:to-rose-600 text-white rounded-xl py-4 font-bold flex flex-col items-center justify-center gap-3 transition-all shadow-lg shadow-rose-500/20 group border border-rose-500/30">
                                        <div className="p-3 bg-white/20 rounded-full group-hover:scale-110 transition-transform">
                                            <Music size={32} />
                                        </div>
                                        <div className="text-center">
                                            <span className="text-lg block">{ui.headers.simulate}</span>
                                        </div>
                                    </button>
                                    <button onClick={() => setShowImageFlow(true)} className="flex-1 bg-gradient-to-br from-indigo-600 to-indigo-700 hover:from-indigo-500 hover:to-indigo-600 text-white rounded-xl py-4 font-bold flex flex-col items-center justify-center gap-3 transition-all shadow-lg shadow-indigo-500/20 group border border-indigo-500/30">
                                        <div className="p-3 bg-white/20 rounded-full group-hover:scale-110 transition-transform">
                                            <ImageIcon size={32} />
                                        </div>
                                        <div className="text-center">
                                            <span className="text-lg block">{ui.headers.visual}</span>
                                        </div>
                                    </button>
                                </div>
                             </div>
                        </div>
                    )}

                    {currentView === 'DICTIONARY' && (
                        <div className="max-w-4xl mx-auto md:p-8 space-y-8">
                            <h2 className="text-3xl font-bold flex items-center gap-3 text-emerald-500"><BookOpen size={32}/> {ui.nav.dictionary}</h2>
                            <div className="flex gap-4">
                                <input value={dictionaryQuery} onChange={e => setDictionaryQuery(e.target.value)} onKeyDown={e => e.key === 'Enter' && handleDictionarySearch()} className={`flex-1 ${tc.bgCard} border ${tc.border} rounded-xl px-4 py-3 text-lg focus:ring-2 focus:ring-emerald-500/50 ${tc.text}`} placeholder="Enter word to rhyme..." />
                                <button onClick={handleDictionarySearch} disabled={isAiLoading} className="bg-emerald-600 hover:bg-emerald-700 text-white px-8 rounded-xl font-bold">Search</button>
                            </div>
                            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
                                {isAiLoading && <div className="col-span-full text-center py-10 text-emerald-500 animate-pulse">Searching rhymes...</div>}
                                {dictionaryResults.map((res, i) => (
                                    <div key={i} className={`${tc.bgCard} border ${tc.border} p-4 rounded-xl hover:border-emerald-500/50 transition-colors`}>
                                        <h3 className={`text-xl font-bold ${tc.text} mb-1`}>{res.word}</h3>
                                        <div className={`flex justify-between text-xs ${tc.textMuted} uppercase tracking-wider mb-2`}>
                                            <span>{res.language}</span>
                                        </div>
                                        <p className={`text-sm ${tc.text}`}>{res.meaning}</p>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {currentView === 'GENERATED' && (
                        <div className="max-w-4xl mx-auto md:p-8 space-y-6">
                            <h2 className="text-3xl font-bold text-sky-500 flex items-center gap-3"><Disc size={32}/> {ui.nav.library}</h2>
                            {generatedSongs.length === 0 ? (
                                <div className={`text-center py-20 border-2 border-dashed ${tc.border} rounded-2xl ${tc.textMuted}`}>
                                    <Music size={48} className="mx-auto mb-4 opacity-20"/>
                                    <p>No generated tracks yet.</p>
                                </div>
                            ) : (
                                <div className="space-y-3">
                                    {generatedSongs.map(song => (
                                        <div key={song.id} onClick={() => togglePlay(song)} className={`group p-3 rounded-xl flex items-center gap-4 cursor-pointer transition-all border ${currentSong?.id === song.id ? `${tc.bgCard} border-rose-500` : `${tc.bgCard} border-transparent hover:border-gray-500`}`}>
                                            <div className={`h-16 w-16 rounded-lg ${song.coverColor} flex items-center justify-center shadow-lg`}>
                                                {currentSong?.id === song.id && isPlaying ? <div className="flex gap-1 h-4 items-end"><div className="w-1 bg-white h-full animate-bounce"/></div> : <Music className="text-white/80"/>}
                                            </div>
                                            <div className="flex-1">
                                                <h4 className={`font-bold ${currentSong?.id === song.id ? 'text-rose-500' : tc.text}`}>{song.title}</h4>
                                                <p className={`text-xs ${tc.textMuted}`}>{song.style} • {formatTime(song.duration)}</p>
                                            </div>
                                            <button className={`p-3 rounded-full ${currentSong?.id === song.id ? 'bg-rose-500 text-white' : 'bg-gray-700 text-gray-400 group-hover:text-white'}`}>
                                                {currentSong?.id === song.id && isPlaying ? <Pause size={16} fill="currentColor"/> : <Play size={16} fill="currentColor"/>}
                                            </button>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>
                    )}

                    {currentView === 'NOTES' && (
                        <div className="max-w-4xl mx-auto md:p-8 space-y-6">
                            <h2 className="text-3xl font-bold text-amber-500 flex items-center gap-3"><Layers size={32}/> {ui.nav.notes}</h2>
                            <div className="grid gap-4">
                                {notes.map(note => (
                                    <div key={note.id} className={`${tc.bgCard} border ${tc.border} p-5 rounded-xl hover:shadow-lg transition-all`}>
                                        <div className="flex justify-between items-start mb-2">
                                            <h3 className={`font-bold text-lg ${tc.text}`}>{note.title}</h3>
                                            <span className={`text-xs ${tc.bgInput} px-2 py-1 rounded ${tc.textMuted}`}>{note.type}</span>
                                        </div>
                                        <p className={`text-sm ${tc.textMuted} line-clamp-2 mb-4`}>"{note.summary}"</p>
                                        <button onClick={() => { 
                                            setContentType(note.type); setContent(note.fullContent); setTitle(note.title); setCurrentView('CREATE'); 
                                        }} className="text-xs text-indigo-500 hover:text-indigo-400 font-bold uppercase tracking-wide">Load Content</button>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {currentView === 'SETTINGS' && (
                        <div className="max-w-3xl mx-auto md:p-8 space-y-8">
                            <h2 className={`text-3xl font-bold ${tc.text} flex items-center gap-3`}><Settings size={32} className="text-gray-500"/> {ui.settings.title}</h2>
                            
                            <div className={`${tc.bgCard} border ${tc.border} rounded-2xl overflow-hidden`}>
                                <div className={`p-6 border-b ${tc.border} flex justify-between items-center`}>
                                    <div className="flex items-center gap-3">
                                        <div className={`p-3 rounded-full ${theme === 'dark' ? 'bg-indigo-900/50 text-indigo-400' : 'bg-orange-100 text-orange-500'}`}>
                                            {theme === 'dark' ? <Moon size={24}/> : <Sun size={24}/>}
                                        </div>
                                        <div>
                                            <h3 className={`font-bold ${tc.text}`}>{ui.settings.theme}</h3>
                                            <p className={`text-xs ${tc.textMuted}`}>Switch between Dark and Light mode</p>
                                        </div>
                                    </div>
                                    <div className="flex gap-2 bg-gray-800 p-1 rounded-lg">
                                        <button onClick={() => setTheme('light')} className={`px-4 py-2 rounded-md text-sm font-bold transition-all ${theme === 'light' ? 'bg-white text-black shadow' : 'text-gray-400 hover:text-white'}`}>Light</button>
                                        <button onClick={() => setTheme('dark')} className={`px-4 py-2 rounded-md text-sm font-bold transition-all ${theme === 'dark' ? 'bg-gray-700 text-white shadow' : 'text-gray-400 hover:text-white'}`}>Dark</button>
                                    </div>
                                </div>

                                <div className={`p-6 border-b ${tc.border} flex justify-between items-center`}>
                                    <div className="flex items-center gap-3">
                                        <div className="p-3 rounded-full bg-blue-900/50 text-blue-400"><Globe size={24}/></div>
                                        <div>
                                            <h3 className={`font-bold ${tc.text}`}>{ui.settings.language}</h3>
                                            <p className={`text-xs ${tc.textMuted}`}>Choose your interface language</p>
                                        </div>
                                    </div>
                                    <select value={appLanguage} onChange={(e) => setAppLanguage(e.target.value as any)} className={`bg-gray-800 text-white border border-gray-700 rounded-lg px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500`}>
                                        <option value="English">English</option>
                                        <option value="Nepali">नेपाली</option>
                                        <option value="Hindi">हिंदी</option>
                                    </select>
                                </div>

                                <div className={`p-6 flex justify-between items-center`}>
                                    <div className="flex items-center gap-3">
                                        <div className="p-3 rounded-full bg-green-900/50 text-green-400"><TypeIcon size={24}/></div>
                                        <div>
                                            <h3 className={`font-bold ${tc.text}`}>{ui.settings.fontSize}</h3>
                                            <p className={`text-xs ${tc.textMuted}`}>Adjust text size for better readability</p>
                                        </div>
                                    </div>
                                    <div className="flex gap-2">
                                        {(['small', 'medium', 'large'] as const).map(s => (
                                            <button 
                                                key={s} 
                                                onClick={() => setFontSize(s)}
                                                className={`px-4 py-2 border rounded-lg text-xs font-bold capitalize ${fontSize === s ? 'bg-gray-700 text-white border-gray-600' : `text-gray-500 border-gray-800 hover:border-gray-600`}`}
                                            >
                                                {s}
                                            </button>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}
                    
                     {currentView === 'ABOUT' && (
                        <div className="max-w-3xl mx-auto md:p-8 space-y-8">
                             {/* Hero Section */}
                            <div className="text-center space-y-6">
                                <div className="h-24 w-24 bg-gradient-to-br from-rose-600 to-indigo-700 rounded-3xl mx-auto flex items-center justify-center shadow-2xl mb-6">
                                    <Wand2 size={48} className="text-white" />
                                </div>
                                <h2 className={`text-4xl font-bold ${tc.text}`}>{ui.about.title}</h2>
                                <p className={`${tc.textMuted} leading-relaxed max-w-xl mx-auto`}>
                                    NEPCON AI Pro connects the rich cultural heritage of South Asia with the boundless potential of Generative AI. 
                                    Whether you are writing the next hit Lok Dohori, a heart-touching Ghazal, or a cinematic script, we provide the tools to amplify your creativity.
                                </p>
                            </div>

                             {/* Detailed Info Cards */}
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div className={`p-6 ${tc.bgCard} rounded-xl border ${tc.border}`}>
                                    <h4 className="font-bold text-rose-500 mb-2 flex items-center gap-2"><Music size={18}/> Cultural Context</h4>
                                    <p className={`text-sm ${tc.textMuted}`}>Deeply optimized for Nepali and Hindi nuances, metaphors, and rhyming structures unlike generic AI models.</p>
                                </div>
                                <div className={`p-6 ${tc.bgCard} rounded-xl border ${tc.border}`}>
                                    <h4 className="font-bold text-indigo-500 mb-2 flex items-center gap-2"><ImageIcon size={18}/> Visual Storytelling</h4>
                                    <p className={`text-sm ${tc.textMuted}`}>Turn your text into breakdown prompts for visual media, ready for storyboarding and production.</p>
                                </div>
                            </div>

                            {/* FAQs Section */}
                            <div className="space-y-4">
                                <h3 className={`text-2xl font-bold ${tc.text} flex items-center gap-2 border-b ${tc.border} pb-4`}><HelpCircle size={24}/> {ui.about.faq}</h3>
                                {FAQS.map((faq, index) => (
                                    <div key={index} className={`${tc.bgCard} border ${tc.border} rounded-xl overflow-hidden`}>
                                        <button 
                                            onClick={() => setExpandedFaqIndex(expandedFaqIndex === index ? null : index)}
                                            className={`w-full p-4 flex justify-between items-center text-left hover:${tc.bgInput} transition-colors`}
                                        >
                                            <span className={`font-bold ${tc.text}`}>{faq.q}</span>
                                            {expandedFaqIndex === index ? <ChevronUp size={20} className={tc.textMuted}/> : <ChevronDown size={20} className={tc.textMuted}/>}
                                        </button>
                                        {expandedFaqIndex === index && (
                                            <div className={`p-4 pt-0 text-sm ${tc.textMuted} border-t ${tc.border} ${tc.bgSidebar}`}>
                                                {faq.a}
                                            </div>
                                        )}
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}
                </div>

                {/* Player Bar */}
                {currentSong && (
                    <div className={`h-20 ${tc.bgSidebar} border-t ${tc.border} px-6 flex items-center justify-between z-30`}>
                        <div className="flex items-center gap-4 w-1/3">
                            <div className={`h-12 w-12 rounded bg-gray-800 ${currentSong.coverColor} flex items-center justify-center`}><Music size={20} className="text-white/80"/></div>
                            <div className="min-w-0">
                                <div className={`font-bold text-sm truncate ${tc.text}`}>{currentSong.title}</div>
                                <div className={`text-xs ${tc.textMuted} truncate`}>{currentSong.style}</div>
                            </div>
                        </div>
                        <div className="flex flex-col items-center flex-1">
                            <div className="flex items-center gap-6">
                                <button className={`${tc.textMuted} hover:${tc.text}`}><SkipBack size={20}/></button>
                                <button onClick={() => togglePlay(currentSong)} className={`w-8 h-8 rounded-full ${theme === 'dark' ? 'bg-white text-black' : 'bg-black text-white'} flex items-center justify-center hover:scale-105 transition-transform`}>
                                    {isPlaying ? <Pause size={16} fill="currentColor"/> : <Play size={16} fill="currentColor" className="ml-0.5"/>}
                                </button>
                                <button className={`${tc.textMuted} hover:${tc.text}`}><SkipForward size={20}/></button>
                            </div>
                            <div className={`w-full max-w-md flex items-center gap-3 mt-1 text-xs font-mono ${tc.textMuted}`}>
                                <span>{formatTime(currentTime)}</span>
                                <div className="flex-1 h-1 bg-gray-700 rounded-full overflow-hidden">
                                    <div className="h-full bg-rose-500 transition-all duration-1000 ease-linear" style={{ width: `${(currentTime / duration) * 100}%` }}></div>
                                </div>
                                <span>{formatTime(duration)}</span>
                            </div>
                        </div>
                        <div className={`w-1/3 flex justify-end gap-3 ${tc.textMuted}`}>
                             <Volume2 size={18} />
                             <Share2 size={18} className={`hover:${tc.text} cursor-pointer`}/>
                             <Download size={18} className={`hover:${tc.text} cursor-pointer`}/>
                        </div>
                    </div>
                )}
            </div>

            {/* Maximized Text Area Overlay */}
            {maximizedSection && (
                 <div className="fixed inset-0 z-[60] bg-gray-950 flex flex-col animate-in fade-in duration-200">
                    <div className={`flex justify-between items-center p-4 border-b ${tc.border} ${tc.bgSidebar}`}>
                        <h3 className={`font-bold text-lg ${tc.text}`}>
                            {maximizedSection === 'DRAFTER' ? ui.headers.aiDrafter : maximizedSection === 'RESULT' ? ui.headers.result : 'Edit Prompt'}
                        </h3>
                        <div className="flex gap-4 items-center">
                            {maximizedSection === 'DRAFTER' && (
                                <button onClick={handleAiContentGeneration} disabled={isAiLoading || !aiPrompt.trim()} className="px-4 py-2 bg-rose-600 rounded-lg text-white text-sm font-bold flex gap-2 items-center">
                                     {isAiLoading ? <Loader2 size={14} className="animate-spin"/> : <Sparkles size={14} />} Generate
                                </button>
                            )}
                            <button onClick={() => setMaximizedSection(null)} className={`p-2 hover:${tc.bgInput} rounded-full ${tc.text}`}><Minimize2 size={20}/></button>
                        </div>
                    </div>
                    <div className="flex-1 p-4 overflow-hidden">
                         {maximizedSection === 'DRAFTER' && (
                             <textarea value={aiPrompt} onChange={e => setAiPrompt(e.target.value)} className={`w-full h-full resize-none bg-transparent focus:outline-none ${tc.text} text-lg p-4 font-mono leading-relaxed`} placeholder="Start drafting..."/>
                         )}
                         {maximizedSection === 'RESULT' && (
                             <textarea value={content} onChange={e => setContent(e.target.value)} className={`w-full h-full resize-none bg-transparent focus:outline-none ${tc.text} text-lg p-4 font-mono leading-relaxed`} placeholder="Content result..."/>
                         )}
                         {maximizedSection === 'SB_PROMPT' && imagePrompts[selectedImagePromptIndex] && (
                             <textarea value={imagePrompts[selectedImagePromptIndex].prompt} onChange={e => handlePromptChange(selectedImagePromptIndex, e.target.value)} className={`w-full h-full resize-none bg-transparent focus:outline-none ${tc.text} text-lg p-4 font-mono leading-relaxed`}/>
                         )}
                    </div>
                 </div>
            )}

            {/* Music Options Modal */}
            {showMusicOptions && (
                <div className="fixed inset-0 bg-black/80 z-50 flex items-center justify-center p-4 backdrop-blur-sm">
                    <div className={`${tc.bgCard} border ${tc.border} rounded-2xl p-6 w-full max-w-sm space-y-4 shadow-2xl`}>
                        <h3 className={`text-xl font-bold flex items-center gap-2 ${tc.text}`}><Disc className="text-rose-500"/> Generate Audio</h3>
                        <p className={`text-sm ${tc.textMuted}`}>Choose how to realize this composition.</p>
                        <button onClick={handleSimulateMusic} className="w-full py-3 bg-rose-600 hover:bg-rose-700 text-white rounded-xl font-bold flex items-center justify-center gap-2">
                            <Music size={18}/> Simulate Generation
                        </button>
                        <button className="w-full py-3 bg-gray-700 rounded-xl text-gray-400 font-bold flex items-center justify-center gap-2 cursor-not-allowed opacity-60">
                            <Link size={18}/> Export to Suno (Coming Soon)
                        </button>
                        <button onClick={() => setShowMusicOptions(false)} className={`w-full py-2 text-sm ${tc.textMuted} hover:${tc.text}`}>Cancel</button>
                    </div>
                </div>
            )}

            {/* Visual Storyboard Modal */}
            {showImageFlow && (
                <div className="fixed inset-0 bg-black/90 z-50 flex justify-center items-center p-4 md:p-8 backdrop-blur-sm overflow-hidden flex-col">
                     <div className="absolute top-4 right-4 z-50 flex gap-3">
                         <button onClick={() => setIsMobileSceneListOpen(!isMobileSceneListOpen)} className="md:hidden text-gray-400 hover:text-white bg-gray-800/50 p-2 rounded-full backdrop-blur-sm">
                            <List size={24}/>
                         </button>
                         <button onClick={() => setShowImageFlow(false)} className="text-gray-400 hover:text-white bg-gray-800/50 p-2 rounded-full backdrop-blur-sm"><X size={24}/></button>
                     </div>
                     
                     <div className="w-full h-full max-w-7xl flex flex-col md:flex-row gap-6 overflow-hidden relative">
                         {/* Scene List - Overlay on Mobile */}
                         <div className={`
                             absolute md:relative inset-0 z-40 bg-gray-900 md:bg-transparent flex-col h-full gap-4 shrink-0 min-h-0 transition-transform duration-300 md:translate-x-0 w-full md:w-1/3
                             ${isMobileSceneListOpen ? 'translate-x-0 flex' : '-translate-x-full hidden md:flex'}
                         `}>
                            <div className={`${tc.bgCard} border ${tc.border} p-6 rounded-2xl flex-1 flex flex-col overflow-hidden shadow-2xl h-full`}>
                                <div className="flex justify-between items-center mb-4 shrink-0">
                                    <h3 className="text-2xl font-bold text-indigo-400 flex items-center gap-2"><ImageIcon/> Storyboard</h3>
                                    <button onClick={() => setIsMobileSceneListOpen(false)} className="md:hidden text-gray-400"><X size={20}/></button>
                                </div>
                                <div className="flex gap-2 mb-4 shrink-0">
                                    <input type="number" min="1" max="10" value={promptCount} onChange={e => setPromptCount(parseInt(e.target.value))} className={`w-16 ${tc.bgInput} border ${tc.borderInput} rounded-lg px-2 py-1 text-center ${tc.text}`} />
                                    <button onClick={handleBreakdownContent} disabled={isImagePrompting} className="flex-1 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg font-bold text-sm flex items-center justify-center gap-2">
                                        {isImagePrompting ? <div className="animate-spin h-4 w-4 border-2 border-white rounded-full border-t-transparent"/> : <Sparkles size={14}/>} Generate Prompts
                                    </button>
                                </div>
                                {imagePrompts.length > 0 && (
                                    <button 
                                        onClick={isImageGenerating ? handleStopGeneration : handleGenerateAllImages} 
                                        className={`mb-4 w-full border rounded-lg py-2 font-bold text-sm flex items-center justify-center gap-2 transition-all shrink-0 ${isImageGenerating ? 'bg-red-900/50 hover:bg-red-900 border-red-500/30 text-red-300' : 'bg-indigo-900/50 hover:bg-indigo-900 border-indigo-500/30 text-indigo-300'}`}
                                    >
                                        {isImageGenerating ? <Square size={14} fill="currentColor"/> : <Sparkles size={14}/>} 
                                        {isImageGenerating ? 'Stop Generation' : 'Generate All Scenes'}
                                    </button>
                                )}
                                <div className="flex-1 overflow-y-auto space-y-2 pr-2 custom-scrollbar">
                                    {imagePrompts.map((p, i) => (
                                        <div key={i} onClick={() => { setSelectedImagePromptIndex(i); setIsMobileSceneListOpen(false); }} className={`p-3 rounded-xl cursor-pointer border transition-all ${selectedImagePromptIndex === i ? 'bg-indigo-600/20 border-indigo-500' : `${tc.bgInput} border-transparent hover:${tc.bgSidebar}`}`}>
                                            <div className="flex justify-between items-center mb-1">
                                                <span className="text-xs font-bold text-indigo-400">SCENE {p.id}</span>
                                                {p.status === 'loading' && <Loader2 size={12} className="text-indigo-400 animate-spin"/>}
                                                {p.status === 'generated' && <Check size={12} className="text-green-500"/>}
                                                {p.status === 'error' && <X size={12} className="text-red-500"/>}
                                            </div>
                                            <p className={`text-sm ${tc.textMuted} line-clamp-2`}>{p.summary_ne}</p>
                                        </div>
                                    ))}
                                    {imagePrompts.length === 0 && <div className={`text-center ${tc.textMuted} mt-10`}>Generate prompts to start.</div>}
                                </div>
                            </div>
                         </div>

                         <div className="w-full md:w-2/3 flex flex-col h-full gap-4 shrink-0 min-h-0 overflow-y-auto md:overflow-hidden z-0">
                            <div className={`flex-1 ${tc.bgCard} border ${tc.border} rounded-2xl overflow-hidden relative flex flex-col min-h-[400px]`}>
                                {imagePrompts[selectedImagePromptIndex]?.status === 'loading' && (
                                    <div className="absolute inset-0 bg-black/60 z-10 flex flex-col items-center justify-center">
                                        <div className="animate-spin h-10 w-10 border-4 border-indigo-500 border-t-transparent rounded-full mb-4"></div>
                                        <p className="text-indigo-400 font-mono animate-pulse">Rendering Scene...</p>
                                    </div>
                                )}
                                
                                <div className={`flex-1 relative overflow-auto ${imageFitMode === 'contain' ? 'flex items-center justify-center p-4' : 'block'}`}>
                                     {imagePrompts[selectedImagePromptIndex]?.imageUrl ? (
                                        <img 
                                            src={imagePrompts[selectedImagePromptIndex].imageUrl} 
                                            alt="Generated Scene" 
                                            className={`${imageFitMode === 'contain' ? 'max-w-full max-h-full object-contain' : 'w-full h-auto object-cover'}`} 
                                        />
                                     ) : (
                                        <div className={`text-center ${tc.textMuted} absolute inset-0 flex flex-col items-center justify-center`}>
                                            <ImageIcon size={64} className="mx-auto mb-4 opacity-20"/>
                                            <p>Select a scene prompt to render.</p>
                                            {isMobileSceneListOpen === false && (
                                                <button onClick={() => setIsMobileSceneListOpen(true)} className="mt-4 md:hidden text-indigo-400 flex items-center gap-2 text-sm border border-indigo-500/30 px-4 py-2 rounded-full">
                                                    <List size={16}/> Select from List
                                                </button>
                                            )}
                                        </div>
                                     )}
                                </div>

                                {imagePrompts[selectedImagePromptIndex]?.imageUrl && (
                                    <div className="absolute top-4 right-4 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity z-20">
                                        <button 
                                            onClick={() => setImageFitMode(prev => prev === 'contain' ? 'cover' : 'contain')}
                                            title="Toggle Zoom"
                                            className="p-2 bg-black/50 text-white rounded-lg hover:bg-black/80 backdrop-blur-sm transition-colors"
                                        >
                                            {imageFitMode === 'contain' ? <ZoomIn size={20}/> : <ZoomOut size={20}/>}
                                        </button>
                                        <button 
                                            onClick={() => handleDownloadImage(imagePrompts[selectedImagePromptIndex].imageUrl!, imagePrompts[selectedImagePromptIndex].id)} 
                                            title="Download"
                                            className="p-2 bg-black/50 text-white rounded-lg hover:bg-black/80 backdrop-blur-sm transition-colors"
                                        >
                                            <Download size={20}/>
                                        </button>
                                    </div>
                                )}
                            </div>
                            
                            {imagePrompts.length > 0 && (
                                <div className={`${tc.bgCard} border ${tc.border} p-4 rounded-2xl flex flex-col gap-3 shrink-0 shadow-lg`}>
                                    <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-2">
                                        <label className={`text-xs ${tc.textMuted} uppercase font-bold flex items-center gap-2`}><Edit3 size={12}/> Edit Prompt (English)</label>
                                        <div className="flex gap-2 w-full sm:w-auto">
                                            <button onClick={() => setMaximizedSection('SB_PROMPT')} className="text-xs text-indigo-500 hover:text-indigo-400 p-2 border border-indigo-500/20 rounded-lg"><Maximize2 size={14}/></button>
                                            
                                            {/* Generate Selected Button */}
                                            <button 
                                                onClick={handleGenerateImage} 
                                                disabled={isImageGenerating} 
                                                className="flex-1 sm:flex-none px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg font-bold flex items-center justify-center gap-2 text-xs shadow-lg shadow-indigo-500/20 whitespace-nowrap"
                                            >
                                                {imagePrompts[selectedImagePromptIndex]?.status === 'generated' ? <RefreshCw size={14}/> : <ImageIcon size={14}/>} 
                                                {imagePrompts[selectedImagePromptIndex]?.status === 'generated' ? 'Regenerate Scene' : 'Render Scene'}
                                            </button>

                                            {/* Generate All Button (Added here as well for convenience) */}
                                            <button 
                                                onClick={isImageGenerating ? handleStopGeneration : handleGenerateAllImages} 
                                                disabled={isImageGenerating && !stopGenerationRef.current}
                                                className={`flex-1 sm:flex-none px-4 py-2 border rounded-lg font-bold flex items-center justify-center gap-2 text-xs transition-all whitespace-nowrap ${isImageGenerating ? 'bg-red-900/50 text-red-300 border-red-500/30' : 'bg-indigo-900/50 text-indigo-300 border-indigo-500/30 hover:bg-indigo-900'}`}
                                            >
                                                {isImageGenerating ? <Square size={14} fill="currentColor"/> : <Sparkles size={14}/>} 
                                                {isImageGenerating ? 'Stop' : 'All'}
                                            </button>
                                        </div>
                                    </div>
                                    <textarea 
                                        value={imagePrompts[selectedImagePromptIndex]?.prompt || ''}
                                        onChange={(e) => handlePromptChange(selectedImagePromptIndex, e.target.value)}
                                        className={`w-full ${tc.bgInput} border ${tc.borderInput} rounded-lg p-3 text-sm ${tc.text} focus:outline-none focus:ring-2 focus:ring-indigo-500 resize-none h-20`}
                                    />
                                </div>
                            )}
                         </div>
                     </div>
                </div>
            )}
        </div>
    );
}